# Generated by Django 5.1.4 on 2025-01-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20250111_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventry',
            new_name='inventory',
        ),
    ]
